src/GiveCRM.Admin.Web/ViewModels/SignUp/Complete.cs
using System.ComponentModel.DataAnnotations;
using GiveCRM.Admin.Web.Interfaces;

namespace GiveCRM.Admin.Web.ViewModels.SignUp
{
    public class Complete : IAdditionalInfo, IConfiguration
    {
        //IAdditionalInfo
        public string UserName { get; set; }
        public string RegisteredCharityNumber { get; set; }
        [Required(ErrorMessage = "Please enter a subdomain")]
        public string SubDomain { get; set; }

        //IConfiguration
        public string BaseDomain { get; set; }
        public string ExcelTemplatePath { get; set; }

        public Complete WithConfig(IConfiguration configuration)
        {
            BaseDomain = configuration.BaseDomain;
            ExcelTemplatePath = configuration.ExcelTemplatePath;
            return this;
        }
    }
}

src/GiveCRM.Admin.Web/ViewModels/SignUp/CompleteViewModel.cs
using System.ComponentModel.DataAnnotations;
using GiveCRM.Admin.Web.Interfaces;

namespace GiveCRM.Admin.Web.ViewModels.SignUp
{
    public class CompleteViewModel
    {
        //IAdditionalInfo
        public string UserName { get; set; }
        public string RegisteredCharityNumber { get; set; }
        [Required(ErrorMessage = "Please enter a subdomain")]
        public string SubDomain { get; set; }

        public string BaseDomain { get; set; }
        public string ExcelTemplatePath { get; set; }
        public string CrmTestUrl { get; set; }

        public CompleteViewModel WithConfig(IConfiguration configuration)
        {
            BaseDomain = configuration.BaseDomain;
            ExcelTemplatePath = configuration.ExcelTemplatePath;
            CrmTestUrl = configuration.CrmTestUrl;
            return this;
        }
    }
}

src/GiveCRM.Admin.Web/ViewModels/SignUp/EmailViewModel.cs
namespace GiveCRM.Admin.Web.ViewModels.SignUp
{
    public class EmailViewModel
    {
        public string To { get; set; }
        public string ActivationToken { get; set; }
    }
}

src/GiveCRM.Admin.Web/ViewModels/SignUp/RequiredInfo.cs
using System.ComponentModel.DataAnnotations;

namespace GiveCRM.Admin.Web.ViewModels.SignUp
{
    public class RequiredInfo
    {
        [Required(ErrorMessage = "Please enter your email address")]
        [Display(Name = "Email Address")]
        public string UserIdentifier { get; set; }
        [Required(ErrorMessage = "Please enter a password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please enter the name of your charity")]
        [Display(Name = "Charity Name")]
        public string CharityName { get; set; }
        [Required(ErrorMessage = "Please accept the terms and conditions")]
        [Display(Name = "Terms and Conditions")]
        public bool TermsAccepted { get; set; }
    }
}

src/GiveCRM.Admin.Web/ViewModels/SignUp/RequiredInfoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GiveCRM.Admin.Web.ViewModels.SignUp
{
    public class RequiredInfoViewModel
    {
        [Required(ErrorMessage = "Please enter your email address")]
        [Display(Name = "Email Address")]
        public string UserIdentifier { get; set; }
        [Required(ErrorMessage = "Please enter a password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please enter the name of your charity")]
        [Display(Name = "Charity Name")]
        public string CharityName { get; set; }
        [Required(ErrorMessage = "Please accept the terms and conditions")]
        [Display(Name = "Terms and Conditions")]
        public bool TermsAccepted { get; set; }
    }
}

src/GiveCRM.Admin.Web/ViewModels/SignUp/StartSiteViewModel.cs
namespace GiveCRM.Admin.Web.ViewModels.SignUp
{
    public class StartSiteViewModel
    {
        public string Url { get; set; }
        public string SubDomain { get; set; }
    }
}

src/GiveCRM.Admin.Web/Controllers/SignUpController.cs
using System;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using GiveCRM.Admin.BusinessLogic;
using GiveCRM.Admin.Models;
using GiveCRM.Admin.Web.Extensions;
using GiveCRM.Admin.Web.Helpers;
using GiveCRM.Admin.Web.Interfaces;
using GiveCRM.Admin.Web.Services;
using GiveCRM.Admin.Web.ViewModels.SignUp;
using IConfiguration = GiveCRM.Admin.Web.Interfaces.IConfiguration;

namespace GiveCRM.Admin.Web.Controllers
{
    public class SignUpController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly ISignUpQueueingService signUpQueueingService;
        private readonly ICharityMembershipService charityMembershipService;
        private readonly IMembershipService membershipService;

        public SignUpController(IConfiguration configuration, ISignUpQueueingService signUpQueueingService, ICharityMembershipService charityMembershipService, IMembershipService membershipService)
        {
            if (configuration == null)
            {
                throw new ArgumentNullException("configuration");
            }

            if (signUpQueueingService == null)
            {
                throw new ArgumentNullException("signUpQueueingService");
            }

            if (charityMembershipService == null)
            {
                throw new ArgumentNullException("charityMembershipService");
            }

            if (membershipService == null)
            {
                throw new ArgumentNullException("membershipService");
            }

            this.configuration = configuration;
            this.signUpQueueingService = signUpQueueingService;
            this.charityMembershipService = charityMembershipService;
            this.membershipService = membershipService;
        }

        [HttpGet]
        public ActionResult SignUp()
        {
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult SignUp(RequiredInfoViewModel requiredInfoViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(requiredInfoViewModel);
            }

            var subDomain = GetSubDomainFromCharityName(requiredInfoViewModel.CharityName);
            var activationToken = TokenHelper.CreateRandomIdentifier();

            var registrationInfo = new RegistrationInfo();
            Mapper.DynamicMap(requiredInfoViewModel, registrationInfo);

            string userIdentifier = registrationInfo.UserIdentifier;
            var userRegistrationStatus = membershipService.CreateUser(userIdentifier, registrationInfo.Password, userIdentifier);
            if (userRegistrationStatus == UserCreationResult.DuplicateEmail)
            {
                ModelState.AddModelError("UserIdentifier",
                                         "You have already registered with GiveCRM.  Would you like to log in instead?");
                return View(requiredInfoViewModel);
            }

            if (userRegistrationStatus == UserCreationResult.Success)
            {
                bool result = CreateCharity(registrationInfo);

                if (result)
                {
                    ProvisionService(requiredInfoViewModel, activationToken);
                    TempData["SubDomain"] = subDomain;

                    return RedirectToAction("Complete");
                }

                ModelState.AddModelError("", "Charity registration failed. Please contact support.");
                return View();
            }

            ModelState.AddModelError("", "User registration failed. Please contact support.");
            return View();
        }

        private void ProvisionService(RequiredInfoViewModel requiredInfoViewModel, Guid activationToken)
        {
            var emailViewModel = new EmailViewModel
                                     {
                                         To = requiredInfoViewModel.UserIdentifier,
                                         ActivationToken = activationToken.AsQueryString()
                                     };

            signUpQueueingService.QueueEmail(emailViewModel);
            signUpQueueingService.QueueProvisioning();
        }

        private bool CreateCharity(RegistrationInfo registrationInfo)
        {
            var membershipUser = membershipService.GetUser(registrationInfo.UserIdentifier);
            if (membershipUser != null)
            {
                var user = new User {Email = membershipUser.Email, Username = membershipUser.UserName};
                return charityMembershipService.RegisterCharityWithUser(registrationInfo, user);
            }

            return false;
        }

        [HttpGet]
        public ActionResult Complete()
        {
            var subDomain = TempData["SubDomain"] as string;

            var viewModel = new CompleteViewModel
                                {
                                    SubDomain = subDomain
                                }.WithConfig(configuration);

            return View(viewModel);
        }

        private static string GetSubDomainFromCharityName(string charityName)
        {
            var result = Regex.Replace(charityName, @"[\s]", "-");
            return Regex.Replace(result, @"[^\w-]", "");
        }

        [HttpPost]
        public ActionResult StoreAdditionalInfo(CompleteViewModel completeViewModel)
        {
            var viewModel = completeViewModel.WithConfig(configuration);

            if (!ModelState.IsValid)
            {
                return View("Complete", viewModel);
            }

            return View("Complete", viewModel);
        }

        public ActionResult StartSite(string id)
        {
            var subDomain = GetSubDomainFromActivationToken(id);

            var viewModel = new StartSiteViewModel
                                {
                                    Url = configuration.CrmTestUrl,
                                    SubDomain = subDomain
                                };

            return View(viewModel);
        }

        private string GetSubDomainFromActivationToken(string activationToken)
        {
            //TODO get this from database
            var token = "";
            return token == null ? "" : token.ToString();
        }
    }
}

src/GiveCRM.Admin.Web/Views/SignUp/Complete.cshtml
@model GiveCRM.Admin.Web.ViewModels.SignUp.CompleteViewModel

@{
    ViewBag.Title = "GiveCRM - we're setting up your site";
}

<h2>Thanks, we're setting up your site and we'll email you when it's ready</h2>

<div class="row">
    <div class="span16">
        <h4>While you're waiting, we need a little more information:</h4>
    @using (Html.BeginForm("StoreAdditionalInfo", "SignUp")) {
        <div>
            <fieldset>
                <div class="clearfix">
                    @Html.LabelFor(m => m.UserName, "Your Name")
                    <div class="input">
                        @Html.TextBoxFor(m => m.UserName)
                        @Html.ValidationMessageFor(m => m.UserName)
                    </div>
                </div>

                <div class="clearfix">
                    @Html.LabelFor(m => m.RegisteredCharityNumber, "Registered Charity Number")
                    <div class="input">
                        @Html.TextBoxFor(m => m.RegisteredCharityNumber)
                        @Html.ValidationMessageFor(m => m.RegisteredCharityNumber)
                    </div>
                </div>

                <div class="clearfix">
                    @Html.LabelFor(m => m.SubDomain, "Your Domain Name")
                    <div class="input">
                        http://
                        @Html.TextBoxFor(m => m.SubDomain, new { @class = "span3" })
                        .@Model.BaseDomain
                        @Html.ValidationMessageFor(m => m.SubDomain)
                    </div>
                </div>

                <div class="clearfix">
                    <div class="input">
                        <input type="submit" value="Store" class="btn large primary" />
                    </div>
                </div>
            </fieldset>
        </div>
    }
    </div>

    <div class="span16">
        <div>
            <h4>To upload your customer list, we need the data in our format.</h4>
            <a href="@Model.ExcelTemplatePath">Download the Excel template</a>
        </div>
    </div>
</div>
<script language="javascript">
    $(document).ready(function () {
        $('.field-validation-error').parent().parent().addClass('error');
    });
</script>

src/GiveCRM.Admin.Web/Views/SignUp/SignUp.cshtml
@{
    ViewBag.Title = "GiveCRM";
}

<div class="row">
    <div class="span16">
    @Html.Partial("SignUpForm")
    </div>
</div>

src/GiveCRM.Admin.Web/Views/SignUp/StartSite.cshtml
@model GiveCRM.Admin.Web.ViewModels.SignUp.StartSiteViewModel

@{
    ViewBag.Title = "StartSite";
}

<h1>Your giveCRM site has been activated</h1>
 
<h3>Your site is located at:
<a href="//@Model.Url">@(Model.SubDomain).GiveCRM.org</a>.</h3>
 
<h4>To get started you may want to <a href="/ExcelImport">Import your membership information</a>.</h4>
 
<h4>Otherwise, lets <a href="//@Model.Url">go to your new CRM</a>.</h4>